/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewModel;

import Model.MauSac;
import Model.dongSP;
import Service.Interface.dongSpInterface;
import Service.Interface.mauSacInterface;
import Service.dongSPServices;
import Service.mauSacServices;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JFrameMSvsDSP extends javax.swing.JFrame {

    private DefaultTableModel dtmMS = new DefaultTableModel();
    DefaultTableModel dtmDSP = new DefaultTableModel();

    List<dongSpViewModel> listDSP;
    List<mauSacViewModel> listMS;

    private dongSpInterface dsp1 = new dongSPServices();
    mauSacInterface ms1 = new mauSacServices();

    public JFrameMSvsDSP() {
        initComponents();

        tblDSP.setModel(dtmDSP);
        String[] dsp = {"id dsp", "ma DSP", "ten DSP"};
        dtmDSP.setColumnIdentifiers(dsp);
        txtIDDong.disable();
        listDSP = dsp1.getAll();
        showDataDong(listDSP);

        tblMausac.setModel(dtmMS);
        String[] ms = {"id ms", "ma ms", "ten ms"};
        dtmMS.setColumnIdentifiers(ms);
        txtIDMau.disable();
        showDataMau(ms1.getAll());
    }

    private void showDataDong(List<dongSpViewModel> listdsp) {
        dtmDSP.setRowCount(0);
        for (dongSpViewModel d : listdsp) {
            dtmDSP.addRow(d.toDataRow());
        }
    }

    public dongSP getDataDSP() {
        String ma = txtMaDong.getText();
        String ten = txtTenDong.getText();
        dongSP d = new dongSP(null, ma, ten);
        return d;
    }

    private void fillToTableDSP(int row) {
        dongSpViewModel d = dsp1.getAll().get(row);
        txtIDDong.setText(d.getIdDSP());
        txtMaDong.setText(d.getMaDSP());
        txtTenDong.setText(d.getTenDSP());
    }

    private void showDataMau(List<mauSacViewModel> listms) {
        dtmMS.setRowCount(0);
        for (mauSacViewModel m : listms) {
            dtmMS.addRow(m.toDataRow());
        }
    }

    public MauSac getDataMS() {
        String ma = txtMaMau.getText();
        String ten = txtTenMau.getText();
        MauSac ms = new MauSac(null, ma, ten);
        return ms;
    }

    private void fillToTableMS(int row) {
        mauSacViewModel m = ms1.getAll().get(row);
        txtIDMau.setText(m.getIdMS());
        txtMaMau.setText(m.getMaMS());
        txtTenMau.setText(m.getTenMS());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMauSac = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableDongSP = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaMau = new javax.swing.JTextField();
        txtTenMau = new javax.swing.JTextField();
        btnNewMau = new javax.swing.JButton();
        btnAddMau = new javax.swing.JButton();
        btnUpdateMau = new javax.swing.JButton();
        btndeleteMau = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIDMau = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaDong = new javax.swing.JTextField();
        txtTenDong = new javax.swing.JTextField();
        btnNewDong = new javax.swing.JButton();
        btnAddDong = new javax.swing.JButton();
        btnUpdateDong = new javax.swing.JButton();
        btndeleteDong = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtIDDong = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMausac = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDSP = new javax.swing.JTable();

        jTableMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMauSacMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableMauSac);

        jTableDongSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDongSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDongSPMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableDongSP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Tên Màu");

        jLabel4.setText("Mã Màu");

        btnNewMau.setText("New");
        btnNewMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMauActionPerformed(evt);
            }
        });

        btnAddMau.setText("Add");
        btnAddMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMauActionPerformed(evt);
            }
        });

        btnUpdateMau.setText("Update");
        btnUpdateMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMauActionPerformed(evt);
            }
        });

        btndeleteMau.setText("Delete");
        btndeleteMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteMauActionPerformed(evt);
            }
        });

        jLabel10.setText("ID ");

        txtIDMau.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDMau)
                            .addComponent(txtMaMau, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(txtTenMau))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNewMau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddMau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateMau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeleteMau)
                        .addGap(61, 61, 61))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMau, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMau, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeleteMau)
                    .addComponent(btnUpdateMau)
                    .addComponent(btnAddMau)
                    .addComponent(btnNewMau))
                .addGap(50, 50, 50))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Tên Dòng");

        jLabel6.setText("Mã Dòng");

        btnNewDong.setText("New");
        btnNewDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDongActionPerformed(evt);
            }
        });

        btnAddDong.setText("Add");
        btnAddDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDongActionPerformed(evt);
            }
        });

        btnUpdateDong.setText("Update");
        btnUpdateDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDongActionPerformed(evt);
            }
        });

        btndeleteDong.setText("Delete");
        btndeleteDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteDongActionPerformed(evt);
            }
        });

        jLabel11.setText("ID ");

        txtIDDong.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDDong)
                            .addComponent(txtMaDong, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(txtTenDong))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnNewDong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddDong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateDong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeleteDong)
                        .addGap(61, 61, 61))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDDong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtMaDong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeleteDong)
                    .addComponent(btnUpdateDong)
                    .addComponent(btnAddDong)
                    .addComponent(btnNewDong))
                .addGap(50, 50, 50))
        );

        tblMausac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMausac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMausacMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblMausac);

        tblDSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSPMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblDSP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(497, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMauActionPerformed
        // TODO add your handling code here:
        txtIDMau.setText("");
        txtMaMau.setText("");
        txtTenMau.setText("");
    }//GEN-LAST:event_btnNewMauActionPerformed

    private void btnAddMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMauActionPerformed
        try {
            JOptionPane.showMessageDialog(this, ms1.add(getDataMS()));
            listMS = ms1.getAll();
            showDataMau(listMS);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi nut add");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddMauActionPerformed

    private void btnUpdateMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMauActionPerformed
try {
    int row = tblMausac.getSelectedRow();
    String selectIDMS = tblMausac.getValueAt(row, 0).toString();
            JOptionPane.showMessageDialog(this, ms1.update(getDataMS(), selectIDMS));
            listMS = ms1.getAll();
            showDataMau(listMS);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi nut update");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateMauActionPerformed

    private void btndeleteMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteMauActionPerformed
try {
    int row = tblMausac.getSelectedRow();
    String selectIDMS = tblMausac.getValueAt(row, 0).toString();
            JOptionPane.showMessageDialog(this, ms1.delete(selectIDMS));
            listMS = ms1.getAll();
            showDataMau(listMS);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi nut update");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndeleteMauActionPerformed

    private void btnNewDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDongActionPerformed
        // TODO add your handling code here:
        txtIDDong.setText("");
        txtMaDong.setText("");
        txtTenDong.setText("");
    }//GEN-LAST:event_btnNewDongActionPerformed

    private void btnAddDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDongActionPerformed
 try {
            JOptionPane.showMessageDialog(this, dsp1.add(getDataDSP()));
            listDSP = dsp1.getAll();
           showDataDong(listDSP);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi nut add");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddDongActionPerformed

    private void btnUpdateDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDongActionPerformed
try {
    int row = tblDSP.getSelectedRow();
    String selectIDDSP = tblDSP.getValueAt(row, 0).toString();
            JOptionPane.showMessageDialog(this, dsp1.update(getDataDSP(), selectIDDSP));
           listDSP = dsp1.getAll();
            showDataDong(listDSP);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi nut update");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateDongActionPerformed

    private void btndeleteDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteDongActionPerformed
try {
    int row = tblDSP.getSelectedRow();
    String selectIDDSP = tblDSP.getValueAt(row, 0).toString();
            JOptionPane.showMessageDialog(this, dsp1.delete(selectIDDSP));
           listDSP = dsp1.getAll();
            showDataDong(listDSP);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi nut update");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btndeleteDongActionPerformed

    private void jTableMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMauSacMouseClicked

    }//GEN-LAST:event_jTableMauSacMouseClicked

    private void jTableDongSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDongSPMouseClicked

    }//GEN-LAST:event_jTableDongSPMouseClicked

    private void tblMausacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMausacMouseClicked
        int row = tblMausac.getSelectedRow();
        fillToTableMS(row);
    }//GEN-LAST:event_tblMausacMouseClicked

    private void tblDSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSPMouseClicked
        int row = tblDSP.getSelectedRow();
        fillToTableDSP(row);
    }//GEN-LAST:event_tblDSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMSvsDSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMSvsDSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMSvsDSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMSvsDSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMSvsDSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDong;
    private javax.swing.JButton btnAddMau;
    private javax.swing.JButton btnNewDong;
    private javax.swing.JButton btnNewMau;
    private javax.swing.JButton btnUpdateDong;
    private javax.swing.JButton btnUpdateMau;
    private javax.swing.JButton btndeleteDong;
    private javax.swing.JButton btndeleteMau;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableDongSP;
    private javax.swing.JTable jTableMauSac;
    private javax.swing.JTable tblDSP;
    private javax.swing.JTable tblMausac;
    private javax.swing.JTextField txtIDDong;
    private javax.swing.JTextField txtIDMau;
    private javax.swing.JTextField txtMaDong;
    private javax.swing.JTextField txtMaMau;
    private javax.swing.JTextField txtTenDong;
    private javax.swing.JTextField txtTenMau;
    // End of variables declaration//GEN-END:variables

}
